/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 */

// $start: quickstart-kt-gradle-plugins
plugins {
  id("org.jetbrains.kotlin.jvm") version "1.9.0"
  
  // The versions of the JVM and serialization plugins must be the same
  id("org.jetbrains.kotlin.plugin.serialization") version "1.9.0"

  application
}
// $end

repositories {
  // Use Maven Central for resolving dependencies.
  mavenCentral()
}

dependencies {
  // Use the Kotlin JUnit 5 integration.
  testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

  // Use the JUnit 5 integration.
  testImplementation("org.junit.jupiter:junit-jupiter-engine:5.9.3")

  testRuntimeOnly("org.junit.platform:junit-platform-launcher")

  // This dependency is used by the application.
  implementation("com.google.guava:guava:32.1.1-jre")

  // $start: quickstart-kt-gradle-dependencies
  // Add the polywrap-client and serialization dependency required by the Polywrap Client
  implementation("io.polywrap:polywrap-client:0.10.4")
  implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:1.5.1")
  // $end
}

// Apply a specific Java toolchain to ease working on different environments.
java { toolchain { languageVersion.set(JavaLanguageVersion.of(17)) } }

application {
  // Define the main class for the application.
  mainClass.set("quickstartkt.AppKt")
}

tasks.named<Test>("test") {
  // Use JUnit Platform for unit tests.
  useJUnitPlatform()
}
